[package]
name = "lowifi"
version = "0.1.0"
edition = "2021"

[dependencies]

# Basics
clap = { version = "4.5.18", features = ["derive", "cargo"] }
eyre = "0.6.12"
rand = "0.8.5"

# Async
tokio = { version = "1.40.0", features = ["full"] }
futures = "0.3.30"
arc-swap = "1.7.1"

# Data
reqwest = { version = "0.12.7", features = ["blocking"] }
bytes = "1.7.2"

# Misc
scraper = "0.20.0"
rodio = { version = "0.19.0", features = ["mp3"], default-features = false }
crossterm = "0.28.1"
